### ISSUE TITLE
Docker's API VolumesFrom attribute not supported?

### ISSUE THREAD

**Issue by peteanusergiu** [gesellix/gradle-docker-plugin-example#4]
Hi,

thanks for the plugin. It is doing the job - simplifies a lot the way one can interact with Docker.
On question though: on a fast code inspection I could not find the corresponding Gradle's attribute for Docker's VolumesFrom attribute? 
Missing? 
or
Is Gradle's volumes attribute logic dealing somehow with it?

Thks.

**Comment by gesellix** [comment]
Hi @peteanusergiu ,

there's currently no conventient way to use the `VolumesFrom` attribute. You have to pass it via `containerConfiguration` (assuming you'd like to use the DockerRunTask), which is described in detail at https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-a-container

If you like, I'll add an example to the other examples to get you started.

**Comment by gesellix** [comment]
@peteanusergiu an example has been added now.
The relevant bits for the data-volume are at https://github.com/gesellix/gradle-docker-plugin-example/commit/ec623d717fc4f0654d4bd57961705a4f9149fd25#diff-e017f20b68331c51d20f1038af6b658fR13 and the consuming container need to be confiugred like https://github.com/gesellix/gradle-docker-plugin-example/commit/ec623d717fc4f0654d4bd57961705a4f9149fd25#diff-e017f20b68331c51d20f1038af6b658fR25

The example can be run showing some container inspection details via `./gradlew runContainerWithDataVolume -i`.

Does that help?

**Comment by gesellix** [comment]
I'll close the issue for now. If you have problems getting started, feel free to re-open. Thanks!

**Comment by peteanusergiu** [comment]
All clear. Thanks for your examples. It helps.
