### ISSUE TITLE
remoteDockerHost in build-push-and-run-remotely

### ISSUE THREAD

**Issue by ysb33r** [gesellix/gradle-docker-plugin-example#5]
I cannot figure out where `remoteDockerHost` is initialised in this example: https://github.com/gesellix/gradle-docker-plugin-example/blob/master/build-push-and-run-remotely/build.gradle#L21

**Comment by gesellix** [comment]
There: https://github.com/gesellix/gradle-docker-plugin-example/blob/master/build.gradle#L27

**Comment by gesellix** [comment]
I suppose my answer helped? I'm closing this issue, but feel free to re-open if something still isn't clear.
