### ISSUE TITLE
Cannot push builded image to own remote registry

### ISSUE THREAD

**Issue by ttsz** [gesellix/gradle-docker-plugin-example#6]
Hi Tobias,

I have a private docker registry v2 (something like this: https://docs.docker.com/registry/) and it runs remotely.
I can push/pull images to/from it from CLI via https.
But I didn't tested push it via http because I don't know how to do that.
I need a gradle plugin for docker to manage my images and my private registry and I've found your gesellix/gradle-docker-plugin-example. I can bulid image with is (buildImage task) but I can't push this image to my remote docker registry.
This is the error message: 

````
Executing task ':buildImage' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
docker build
temporary buildContext: /home/xxx/Project/xxx/xxx/build/tmp/buildImage/buildContext_gesselixImage_1_3.tar.gz
docker build
using docker at 'unix:///var/run/docker.sock'
could not use the 'unix' protocol to connect to /var/run/docker.sock - retry.
tag d4frf400c7e5 as 'gesselixImage:1.3'...
docker tag
could not use the 'unix' protocol to connect to /var/run/docker.sock - retry.
:buildImage (Thread[main,5,main]) completed. Took 0.662 secs.
:pushImage (Thread[main,5,main]) started.
:pushImage
Executing task ':pushImage' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
docker push
docker push 'gesselixImage:1.3'
docker tag
using docker at 'unix:///var/run/docker.sock'
could not use the 'unix' protocol to connect to /var/run/docker.sock - retry.
could not use the 'unix' protocol to connect to /var/run/docker.sock - retry.
request failed: 'Error reading document:
java.io.IOException: Server returned HTTP response code: 500 for URL: unix://socket/images/url:5000/gesselixImage/push?tag=1.3'
:pushImage FAILED
:pushImage (Thread[main,5,main]) completed. Took 0.012 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pushImage'.
> java.lang.IllegalStateException: docker push failed
````

How I have to config the registry to make this plugin (push task) work with it? 

my build gradle example:

````
ext {
    localDockerHost = "unix:///var/run/docker.sock" //unix / Linux
    remoteDockerHost = 'https://url.remote:5000'
}

repositories {
    mavenCentral()
    jcenter()
    maven { url "https://plugins.gradle.org/m2/" }
 }

plugins {
  id "com.github.ben-manes.versions" version "0.11.3"
  id "de.gesellix.docker" version "2016-01-13T23-15-28"
}

import de.gesellix.gradle.docker.tasks.*

allprojects {
  apply plugin: 'base'
  apply plugin: "de.gesellix.docker"

  docker {
    dockerHost = localDockerHost
    //dockerHost = System.getProperty('DOCKER_HOST') ?: 'https://127.0.0.1:3128'
//    certPath = System.getProperty('docker.cert.path') ?: "${System.getProperty('user.home')}/.docker/machine/machines/default"
    authConfigPlain = ["username"     : "gesellix",
                       "password"     : "-yet-another-password-",
                       "email"        : "tobias@gesellix.de",
                       "serveraddress": "https://index.docker.io/v1/"]
  }
}

task buildImage(type: DockerBuildTask) {
  //dependsOn rmImage
  dependsOn copyDistribs
  imageName = "gesselixImage:1.3"
  buildContextDirectory = file("./virtualization/")
  //buildContextDirectory = file(".")
}
 // TODO: To be continued

task pushImage(type: DockerPushTask) {
  dependsOn buildImage

  repositoryName = "gesselixImage:1.3"
  registry = "url.remote:5000"
}
````

Thank you in advance,
Regards

Laszlo

**Comment by gesellix** [comment]
First thing to note here is how to configure a registry to be available on non-localhost. You can find details in the [deployment instructions](https://docs.docker.com/registry/deploying/#running-a-domain-registry). [Let’s Encrypt](https://letsencrypt.org/) can help you creating valid certificates without too much hazzle. Though I don't want to advocate an insecure setup, I want to mention that you can also use an insecure registry setup, which is explained in [the docs](https://docs.docker.com/registry/insecure/), too. I hope that helps you to get started.

The next thing to note here are the warnings about `could not use the 'unix' protocol to connect to /var/run/docker.sock - retry.`. They indicate problems connecting to the Docker Engine via Unix Domain Socket. I sadly didn't investigate too much time to find out how or whether they can be fixed from the Docker client/Gradle plugin side, which is why I implemented a retry mechanism. If you could check on your host if there are any performance issues, we could find out what's going wrong.

Now to the actual problem of not being able to push to the private registry: I'll try to reproduce on my local network first and then come back to asap!

**Comment by gesellix** [comment]
@ttsz please also note that I'm working on a similar issue there: https://github.com/gesellix/gradle-docker-plugin/issues/48

**Comment by ttsz** [comment]
Thanks finally I make it work. I change docker daemon to listen on tcp.

But I have another question. How can I force the image push in the pushImage task to overwrite an existing image in the registry?

Thanks in advance
Laszlo

**Comment by gesellix** [comment]
Great that you made it work!

Pushing an image doesn't need to be forced, but the tagging before the actual push has to. AFAIK pushing overrides old tags in the registry without errors.
There's a special case: if you're pushing to a private/explicitly named registry, the plugin actually enforces a new tag for you on your local machine - right before the push. So in other words: I'm be surprised that you encounter problems in this area. Do you have any error messages you can share here?

**Comment by gesellix** [comment]
@ttsz just checking: did the pushImage task work for you?

**Comment by ttsz** [comment]
Hello, Sorry.

Yes this task working correctly for me. 
The solution was, set the docker daemon for runs in tcp mode in /etc/default/docker file.

Thanks

**Comment by gesellix** [comment]
Great, so I suppose your question regarding forced pushes has also been solved? In case there's still something unclear, feel free to re-open this or another issue!

**Comment by ttsz** [comment]
Yes, the force push is work fine!
