### ISSUE TITLE
How use DockerBuildTask when in Docerfile has ARG

### ISSUE THREAD

**Issue by knikitin** [gesellix/gradle-docker-plugin-example#7]
I have Docker file with code:
...
ARG profile
...

How run task DockerBuildTask for fill this arg?

Analog: docker build --build-arg profile=dev -t mygroup/myapp .

**Comment by gesellix** [comment]
Please have a look at [the example](https://github.com/gesellix/gradle-docker-plugin-example/blob/667474ba345a0273b1c0278faaf73fabf2985935/build-with-buildargs/build.gradle). The corresponding Dockerfile can be found [beside the build script](https://github.com/gesellix/gradle-docker-plugin-example/blob/667474ba345a0273b1c0278faaf73fabf2985935/build-with-buildargs/Dockerfile). You'll need to update the plugin first - see https://plugins.gradle.org/plugin/de.gesellix.docker for detailed instructions.

Please leave a note when you have further questions.
Thanks!

**Comment by knikitin** [comment]
Thanks! This is an excellent example.
